jara_2_dev/config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get 'home/errorlogin'
  devise_for :users
  #root
  root to: 'productos#index'

  #rubros
  get 'rubros', to:'rubros#index'
  get 'rubros/new', to:'rubros#new'
  post 'rubros/new', to:'rubros#create', as:'rubros_crear'
  get 'rubros/:id/edit', to:'rubros#edit', as:'rubros_editar'
  put 'rubros/edit', to:'rubros#update', as:'rubros_actualizar'
  delete 'rubros/:id/delete', to:'rubros#destroy', as:'rubros_borrar'

  #productos
  get 'productos', to:'productos#index'
  get 'productos/new', to:'productos#new'
  post 'productos/new', to:'productos#create', as:'productos_crear'
  get 'productos/:id/edit', to:'productos#edit', as:'productos_editar'
  put 'productos/edit', to:'productos#update', as:'productos_actualizar'
  delete 'productos/:id/delete', to:'productos#destroy', as:'productos_borrar'

  #marcas
  get 'marcas', to:'marcas#index'
  get 'marcas/new', to:'marcas#new'
  post 'marcas/new', to:'marcas#create', as:'marcas_crear'
  get 'marcas/:id/edit', to:'marcas#edit', as:'marcas_editar'
  put 'marcas/edit', to:'marcas#update', as:'marcas_actualizar'
  delete 'marcas/:id/delete', to:'marcas#destroy', as:'marcas_borrar'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

jara_2_dev/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

jara_2_dev/app/models/marca.rb
class Marca < ApplicationRecord
    has_many :productos
end

jara_2_dev/app/models/producto.rb
class Producto < ApplicationRecord
    belongs_to :marca
    belongs_to :rubro
end

jara_2_dev/app/models/rubro.rb
class Rubro < ApplicationRecord
    has_many :productos
end

jara_2_dev/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

jara_2_dev/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    # def after_sign_in_path_for(resource)
    #     home_errorlogin_path
    # end
end

jara_2_dev/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end

  def errorlogin
  end
end

jara_2_dev/app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  #inicio
  def index
    @datos=Marca.all()
  end
#nuevo
  def new
    @dato=Marca.new
  end
#creación
  def create
    dato=Marca.new
    dato.nombre= params['marca']['nombre']
    dato.save
    redirect_to marcas_path
  end
#edición
  def edit
    @dato=Marca.find(params['id'])
  end
#actializar
  def update
    dato=Marca.find(params['marca']['id'])
    dato.nombre= params['marca']['nombre']
    dato.save
    redirect_to marcas_path
  end
#borrar
  def destroy
    dato=Marca.find(params['id'])
    dato.destroy
    redirect_to marcas_path
  end
end

jara_2_dev/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  #inicio
  def index
    @datos=Producto.all
  end

  #nuevo
  def new
    @dato=Producto.new
    @rubro=Rubro.all
    @marca=Marca.all
  end

  #creación
  def create
    dato=Producto.new
    dato.nombre= params['producto']['nombre']
    dato.cant_min= params['producto']['cant_min']
    dato.cant_act= params['producto']['cant_act']
    dato.precio= params['producto']['precio']
    dato.activo= params['producto']['activo']
    dato.marca_id= params['producto']['marca_id']
    dato.rubro_id= params['producto']['rubro_id']
    dato.save
    redirect_to productos_path
  end

  #edición
  def edit
    @dato=Producto.find(params['id'])
    @marca=Marca.all
    @rubro=Rubro.all
  end

  #actualizar
  def update
    dato=Producto.find(params['producto']['id'])
    dato.nombre= params['producto']['nombre']
    dato.cant_min= params['producto']['cant_min']
    dato.cant_act= params['producto']['cant_act']
    dato.precio= params['producto']['precio']
    dato.activo= params['producto']['activo']
    dato.marca_id= params['producto']['marca_id']
    dato.rubro_id= params['producto']['rubro_id']
    dato.save
    redirect_to productos_path
  end

  #borrar
  def destroy
    dato=Producto.find(params['id'])
    dato.destroy
    redirect_to productos_path
  end
end

jara_2_dev/app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  #inicio
  def index
    @datos=Rubro.all()
  end
#nuevo
  def new
    @dato=Rubro.new
  end
#creacion
  def create
    dato=Rubro.new
    dato.nombre= params['rubro']['nombre']
    dato.perecedero= params['rubro']['perecedero']
    dato.save
    redirect_to rubros_path
  end
#edicion
  def edit
    @dato=Rubro.find(params['id'])
  end
#actualizar
  def update
    dato=Rubro.find(params['rubro']['id'])
    dato.nombre= params['rubro']['nombre']
    dato.perecedero= params['rubro']['perecedero']
    dato.save
    redirect_to rubros_path
  end
#borrar
  def destroy
    dato=Rubro.find(params['id'])
    dato.destroy
    redirect_to rubros_path
  end
end

jara_2_dev/app/helpers/application_helper.rb
module ApplicationHelper
end

jara_2_dev/app/helpers/home_helper.rb
module HomeHelper
end

jara_2_dev/app/helpers/marcas_helper.rb
module MarcasHelper
end

jara_2_dev/app/helpers/productos_helper.rb
module ProductosHelper
end

jara_2_dev/app/helpers/rubros_helper.rb
module RubrosHelper
end

jara_2_dev/app/views/marcas/edit.html.erb
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #288FFD ;">
  <a class="navbar-brand">Almacén</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/productos">Productos</a>
      <a class="nav-item nav-link active" href="../../marcas">Marcas <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/rubros">Rubros</a>
      <a class="nav-item nav-link"><% if current_user.nil?%>
        <%= link_to new_user_session_path, class: 'btn btn-outline-light' do%>Sign in<%end%>
        <% else %><% if user_signed_in? %>
     <%= current_user.email %>
    <% end %></a>
      <a class="nav-item nav-link"><%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' do %>Log out<%end%>
        <% end %></a>
    </div>
    </div>
  </div>
</nav>
<div class = "container">
<h1 align="center">Editar una Marca</h1>
<br>
<br>
<%= form_with scope: @dato, url: marcas_actualizar_path, method: :PUT do |f| %>    
    <%= f.hidden_field  :id%>   
    <p>Si el nombre ingresado no es enviado, es porque ya existe uno con el mismo nombre</p>
    <p>
 <label>Nombre</label> <br>
 <%= f.text_field :nombre, class: "form-control"%>
 </p>
 <%= f.submit "Enviar", disable_with: 'Submiting...' , class: "btn btn-primary" %>
<% end %>
<br>
<br>
</div>

jara_2_dev/app/views/marcas/index.html.erb
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #288FFD ;">
  <a class="navbar-brand">Almacén</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/productos">Productos</a>
      <a class="nav-item nav-link active" href="#">Marcas <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/rubros">Rubros</a>
      <a class="nav-item nav-link"><% if current_user.nil?%>
        <%= link_to new_user_session_path, class: 'btn btn-outline-light' do%>Sign in<%end%>
        <% else %><% if user_signed_in? %>
     <%= current_user.email %>
    <% end %></a>
      <a class="nav-item nav-link"><%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' do %>Log out<%end%>
        <% end %></a>
    </div>
    </div>
  </div>
</nav>


<div class = "container">

<h1 align="center">Marcas</h1>

<div class = "container">
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <% if user_signed_in? %>
      <td><%= link_to 'Nuevo', marcas_crear_path, class: "btn btn-success" %></td>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @datos.each do |dato|%>
        <td><%= dato.id %></td>
        <td><%= dato.nombre %></td>
        <% if user_signed_in? %>      
        <td><%= link_to 'Editar', marcas_editar_path(dato.id), class: "btn btn-warning" %></td>
        <td><%= link_to 'Borrar', marcas_borrar_path(dato.id), class: "btn btn-danger", method: :delete %></td>
        <%end%>
  </tbody>


<%end%>
</table>
</div>
</div>
</body>
</html>

jara_2_dev/app/views/marcas/new.html.erb
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #288FFD ;">
  <a class="navbar-brand">Almacén</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/productos">Productos</a>
      <a class="nav-item nav-link active" href="../marcas">Marcas <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/rubros">Rubros</a>
      <a class="nav-item nav-link"><% if current_user.nil?%>
        <%= link_to new_user_session_path, class: 'btn btn-outline-light' do%>Sign in<%end%>
        <% else %><% if user_signed_in? %>
     <%= current_user.email %>
    <% end %></a>
      <a class="nav-item nav-link"><%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' do %>Log out<%end%>
        <% end %></a>
    </div>
    </div>
  </div>
</nav>
<div class = "container">

<h1 align="center">Nueva Marca</h1>

 <%= form_with scope: @dato, url: marcas_crear_path do |f| %>
    <p>Si el nombre ingresado no es enviado, es porque ya existe uno con el mismo nombre</p>
    <p>
    <label>Marca</label> <br>
    <%= f.text_field :nombre, class: "form-control"%>
    </p>
    <%= f.submit "Enviar", disable_with: 'Submiting...',class: "btn btn-primary" %>
   <% end %>
<br>
<br>
</div>

jara_2_dev/app/views/productos/index.html.erb
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #288FFD ;">
  <a class="navbar-brand">Almacén</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Productos <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/marcas">Marcas</a>
      <a class="nav-item nav-link" href="/rubros">Rubros</a>
      <a class="nav-item nav-link"><% if current_user.nil?%>
        <%= link_to new_user_session_path, class: 'btn btn-outline-light' do%>Sign in<%end%>
        <% else %><% if user_signed_in? %>
     <%= current_user.email %>
    <% end %></a>
      <a class="nav-item nav-link"><%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' do %>Log out<%end%>
        <% end %></a>
    </div>
  </div>
</nav>


<div class = "container">

<h1 align="center">Productos</h1>

<div class = "container">
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Cantidad mínima</th>
      <th scope="col">Cantidad actual</th>
      <th scope="col">Precio</th>
      <th scope="col">Activo</th>
      <th scope="col">Marca</th>
      <th scope="col">Rubro</th>
      <% if user_signed_in? %>
      <td><%= link_to 'Nuevo', productos_crear_path, class: "btn btn-success" %></td>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @datos.each do |dato|%>
        <td><%= dato.id %></td>
        <td><%= dato.nombre %></td>
        <td><%= dato.cant_min %></td>
        <td><%= dato.cant_act %></td>
        <td><%= dato.precio %></td>
        <td><% if dato.activo == true %>
        <span class = "badge badge-pill badge-success">SI</span>
        <%end%>
        <% if dato.activo == false %>
        <span class = "badge badge-pill badge-danger">NO</span>
        <%end%>
        </td>
        <td><%= dato.marca.nombre %></td>
        <td><%= dato.rubro.nombre %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Editar', productos_editar_path(dato.id), class: "btn btn-warning" %></td>
        <td><%= link_to 'Borrar', productos_borrar_path(dato.id), class: "btn btn-danger", method: :delete %></td>
        <%end%>
  </tbody>


<%end%>
</table>
</div>
</div>
</body>
</html>

jara_2_dev/app/views/productos/new.html.erb
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #288FFD ;">
  <a class="navbar-brand">Almacén</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="../">Productos <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/marcas">Marcas</a>
      <a class="nav-item nav-link" href="/rubros">Rubros</a>
      <a class="nav-item nav-link"><% if current_user.nil?%>
        <%= link_to new_user_session_path, class: 'btn btn-outline-light' do%>Sign in<%end%>
        <% else %><% if user_signed_in? %>
     <%= current_user.email %>
    <% end %></a>
      <a class="nav-item nav-link"><%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' do %>Log out<%end%>
        <% end %></a>
    </div>
  </div>
</nav>
<div class = "container">

<h1 align="center">Productos - Nuevo</h1>

<%= form_with scope: @dato, url: productos_crear_path do |f| %>
 <p>
 <label>Nombre</label> <br>
 <%= f.text_field :nombre, class: "form-control" %>
 </p>
 <p>
 <label>Cantidad Minima</label> <br>
 <%= f.number_field :cant_min, class: "form-control" %>
 </p>
 <p>
 <label>Cantidad actual</label> <br>
 <%= f.number_field :cant_act, class: "form-control" %>
 </p>
 <p>
 <label>precio</label> <br>
 <%= f.number_field :precio, class: "form-control" %>
 </p>
  <p>
 <label>activo</label>
 <%= f.check_box :activo %>
 </p>
  <p>
 <label>Rubro</label> <br>
 <%= f.collection_select(:rubro_id, @rubro.all, :id, :nombre, prompt: true, class: "dropdown-menu")%>
 </p>
   <p>
 <label>Marca</label> <br>
 <%= f.collection_select(:marca_id, @marca.all, :id, :nombre, prompt: true, class: "dropdown-menu")%>
 </p>
 <%= f.submit "Enviar", disable_with: 'Submiting...',class: "btn btn-primary" %>
<% end %>
<br>
<br>
</div>

jara_2_dev/app/views/rubros/index.html.erb
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #288FFD ;">
  <a class="navbar-brand">Almacén</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/productos">Productos</a>
      <a class="nav-item nav-link" href="/marcas">Marcas</a>
      <a class="nav-item nav-link active" href="#">Rubros <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link"><% if current_user.nil?%>
        <%= link_to new_user_session_path, class: 'btn btn-outline-light' do%>Sign in<%end%>
        <% else %><% if user_signed_in? %>
     <%= current_user.email %>
    <% end %></a>
      <a class="nav-item nav-link"><%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' do %>Log out<%end%>
        <% end %></a>
    </div>
    </div>
  </div>
</nav>


<div class = "container">

<h1 align="center">Rubros</h1>

<div class = "container">
<table class="table table-dark" >
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Perecedero</th>
      <% if user_signed_in? %>
      <td><%= link_to 'Nuevo', rubros_crear_path, class: "btn btn-success" %></td>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @datos.each do |dato|%>
        <td><%= dato.id %></td>
        <td><%= dato.nombre %></td>
        <td><% if dato.perecedero == true %>
        <span class = "badge badge-pill badge-danger">SI</span>
        <%end%>
        <% if dato.perecedero == false %>
        <span class = "badge badge-pill badge-success">NO</span>
        <%end%>
        </td>
        
        <% if user_signed_in? %>      
        <td><%= link_to 'Editar', rubros_editar_path(dato.id), class: "btn btn-warning" %></td>
        <td><%= link_to 'Borrar', rubros_borrar_path(dato.id), class: "btn btn-danger", method: :delete %></td>
        <%end%>
  </tbody>


<%end%>
</table>
</div>
</div>
</body>
</html>